export type Category =
  | "Bedsheets"
  | "Mink Blankets"
  | "Cushion Covers"
  | "Pillow Covers"
  | "Summer Sets"
  | "Winter Sets"
  | "Summer Comforters"
  | "Winter Comforters";

export type Product = {
  id: string;
  slug: string;
  name: string;
  category: Category;
  price: number;
  mrp?: number;
  tag?: "New" | "Heirloom" | "Limited" | "Bestseller";
  shortDescription: string;
  description: string;
  fabric: string;
  weave: string;
  origin: string;
  care: string[];
  sizes: string[];
  colors: { name: string; hex: string }[];
  images: string[];
};

export const categories: { name: Category; blurb: string; image: string }[] = [
  {
    name: "Bedsheets",
    blurb: "Long-staple cotton sheets. Crisp by morning, soft by night.",
    image:
      "https://images.unsplash.com/photo-1540518614846-7eded433c457?w=1600&q=80&auto=format&fit=crop",
  },
  {
    name: "Mink Blankets",
    blurb: "Plush mink, embossed and brushed for a velvet hand.",
    image:
      "https://images.unsplash.com/photo-1631049552240-59c37f38802b?w=1600&q=80&auto=format&fit=crop",
  },
  {
    name: "Cushion Covers",
    blurb: "Sofa-ready covers. Hand-finished casings, royal trims.",
    image:
      "https://images.unsplash.com/photo-1592229505726-ca121723b8ef?w=1600&q=80&auto=format&fit=crop",
  },
  {
    name: "Pillow Covers",
    blurb: "Sateen pillow covers. Cool to the touch, quiet on the bed.",
    image:
      "https://images.unsplash.com/photo-1620751852890-a89137ec78b9?w=1600&q=80&auto=format&fit=crop",
  },
  {
    name: "Summer Sets",
    blurb: "Lightweight bedding sets for warm, breathable nights.",
    image:
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=1600&q=80&auto=format&fit=crop",
  },
  {
    name: "Winter Sets",
    blurb: "4 to 10-piece bedding ensembles. Layered for long, cold nights.",
    image:
      "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=1600&q=80&auto=format&fit=crop",
  },
  {
    name: "Summer Comforters",
    blurb: "All-cotton fills. Featherweight loft for warmer rooms.",
    image:
      "https://images.unsplash.com/photo-1606170033648-5d55a3edf314?w=1600&q=80&auto=format&fit=crop",
  },
  {
    name: "Winter Comforters",
    blurb: "Heavy down-alt loft. Quilted shells. Built for January.",
    image:
      "https://images.unsplash.com/photo-1631049307290-bb947b114627?w=1600&q=80&auto=format&fit=crop",
  },
];

const IMG = {
  sheet1: "https://images.unsplash.com/photo-1540518614846-7eded433c457?w=1400&q=80&auto=format&fit=crop",
  sheet2: "https://images.unsplash.com/photo-1612320583049-eabe3c21bd94?w=1400&q=80&auto=format&fit=crop",
  sheet3: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=1400&q=80&auto=format&fit=crop",
  mink1: "https://images.unsplash.com/photo-1631049552240-59c37f38802b?w=1400&q=80&auto=format&fit=crop",
  mink2: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=1400&q=80&auto=format&fit=crop",
  cushion1: "https://images.unsplash.com/photo-1592229505726-ca121723b8ef?w=1400&q=80&auto=format&fit=crop",
  cushion2: "https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=1400&q=80&auto=format&fit=crop",
  pillow1: "https://images.unsplash.com/photo-1620751852890-a89137ec78b9?w=1400&q=80&auto=format&fit=crop",
  pillow2: "https://images.unsplash.com/photo-1583845112203-454c7c0f8b35?w=1400&q=80&auto=format&fit=crop",
  set1: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=1400&q=80&auto=format&fit=crop",
  set2: "https://images.unsplash.com/photo-1631049307290-bb947b114627?w=1400&q=80&auto=format&fit=crop",
  comforter1: "https://images.unsplash.com/photo-1606170033648-5d55a3edf314?w=1400&q=80&auto=format&fit=crop",
  comforter2: "https://images.unsplash.com/photo-1531001389693-3a2630f196aa?w=1400&q=80&auto=format&fit=crop",
};

const ROYAL = { name: "Royal Indigo", hex: "#0f1a66" };
const IVORY = { name: "Ivory Mist", hex: "#f1ead7" };
const MIDNIGHT = { name: "Midnight", hex: "#060a2b" };
const CHAMPAGNE = { name: "Champagne", hex: "#c8a96a" };
const SLATE = { name: "Slate Blue", hex: "#3a4a78" };
const BONE = { name: "Bone", hex: "#ece5d3" };
const PEARL = { name: "Pearl", hex: "#f1ead7" };
const GRAPHITE = { name: "Graphite", hex: "#1a1d28" };
const ROSE = { name: "Heritage Rose", hex: "#9c4a5c" };
const MOSS = { name: "Heirloom Moss", hex: "#3d5641" };
const SAFFRON = { name: "Saffron", hex: "#b9612a" };

export const products: Product[] = [
  // ============ BEDSHEETS (7) ============
  {
    id: "p1",
    slug: "atelier-300tc-sateen-sheet",
    name: "Atelier 300 TC Sateen Sheet",
    category: "Bedsheets",
    price: 4990,
    mrp: 6500,
    tag: "Bestseller",
    shortDescription: "300 TC long-staple cotton sateen flat sheet with two pillow covers.",
    description:
      "The everyday sheet that never feels everyday. Woven in 300 TC long-staple cotton sateen for a smooth, cool finish that softens with each wash.",
    fabric: "300 TC Long-staple Cotton Sateen",
    weave: "Sateen",
    origin: "Coimbatore, India",
    care: ["Cool machine wash", "Tumble dry low", "Iron warm"],
    sizes: ["Single", "Double", "Queen", "King"],
    colors: [PEARL, ROYAL, GRAPHITE],
    images: [IMG.sheet1, IMG.sheet2],
  },
  {
    id: "p2",
    slug: "imperial-400tc-percale-sheet",
    name: "Imperial 400 TC Percale Sheet",
    category: "Bedsheets",
    price: 6490,
    tag: "New",
    shortDescription: "400 TC percale flat sheet, crisp hand and matte finish.",
    description:
      "Percale weave with a quiet, matte hand. Stays cool through the night and presses to a hotel-clean finish.",
    fabric: "400 TC Long-staple Cotton Percale",
    weave: "Percale",
    origin: "Karur, India",
    care: ["Cool machine wash", "Iron damp"],
    sizes: ["Double", "Queen", "King"],
    colors: [IVORY, ROYAL, SLATE],
    images: [IMG.sheet2, IMG.sheet1],
  },
  {
    id: "p3",
    slug: "regalia-fitted-sheet-set",
    name: "Regalia Fitted Sheet Set",
    category: "Bedsheets",
    price: 5290,
    shortDescription: "Deep-pocket fitted sheet with two pillow covers.",
    description:
      "Engineered for thicker mattresses. 35 cm deep pockets, fully elasticated edge, 280 TC cotton percale.",
    fabric: "280 TC Cotton Percale",
    weave: "Percale",
    origin: "Erode, India",
    care: ["Machine wash cold", "Tumble dry low"],
    sizes: ["Queen", "King"],
    colors: [PEARL, MIDNIGHT, BONE],
    images: [IMG.sheet1],
  },
  {
    id: "p4",
    slug: "monsoon-printed-bedsheet",
    name: "Monsoon Printed Bedsheet",
    category: "Bedsheets",
    price: 3490,
    mrp: 4500,
    shortDescription: "Hand-block printed cotton bedsheet, double bed.",
    description:
      "Hand-block printed in Bagru in vegetable-dye indigo. 200 TC pure cotton with a soft, breathable hand.",
    fabric: "200 TC Pure Cotton",
    weave: "Plain weave",
    origin: "Bagru, Rajasthan",
    care: ["Cold wash separately first time", "Mild detergent"],
    sizes: ["Double", "Queen"],
    colors: [ROYAL, IVORY, ROSE],
    images: [IMG.sheet3],
  },
  {
    id: "p5",
    slug: "noble-jacquard-bedsheet",
    name: "Noble Jacquard Bedsheet",
    category: "Bedsheets",
    price: 7490,
    tag: "Heirloom",
    shortDescription: "Tonal jacquard motifs, 350 TC, with two pillow covers.",
    description:
      "A bedsheet with a quiet pattern. Jacquard-woven tonal motifs in 350 TC long-staple cotton — visible only when light catches the weave.",
    fabric: "350 TC Long-staple Cotton",
    weave: "Jacquard",
    origin: "Coimbatore, India",
    care: ["Cool machine wash", "Iron warm on reverse"],
    sizes: ["Queen", "King"],
    colors: [ROYAL, CHAMPAGNE, IVORY],
    images: [IMG.sheet2],
  },
  {
    id: "p6",
    slug: "dynasty-king-bedsheet",
    name: "Dynasty King Bedsheet",
    category: "Bedsheets",
    price: 5990,
    shortDescription: "Oversized king flat sheet with deep drape.",
    description:
      "Cut generously for king beds with full drape over both sides. 300 TC sateen, no shrink at first wash.",
    fabric: "300 TC Cotton Sateen",
    weave: "Sateen",
    origin: "Karur, India",
    care: ["Machine wash cold", "Tumble dry low"],
    sizes: ["King", "Super King"],
    colors: [MIDNIGHT, PEARL, GRAPHITE],
    images: [IMG.sheet1, IMG.sheet2],
  },
  {
    id: "p7",
    slug: "heritage-stripe-bedsheet",
    name: "Heritage Stripe Bedsheet",
    category: "Bedsheets",
    price: 4290,
    shortDescription: "Yarn-dyed champagne stripe on ivory ground.",
    description:
      "Yarn-dyed champagne pinstripe woven into a 280 TC ivory base. Quiet, hotel-grade refinement.",
    fabric: "280 TC Yarn-dyed Cotton",
    weave: "Plain weave",
    origin: "Erode, India",
    care: ["Cold wash", "Iron warm"],
    sizes: ["Double", "Queen", "King"],
    colors: [IVORY, BONE],
    images: [IMG.sheet3],
  },

  // ============ MINK BLANKETS (6) ============
  {
    id: "p8",
    slug: "imperial-double-mink-blanket",
    name: "Imperial Double Mink Blanket",
    category: "Mink Blankets",
    price: 8990,
    mrp: 11500,
    tag: "Bestseller",
    shortDescription: "Double-side embossed mink, 1200 GSM, royal indigo.",
    description:
      "The Imperial Mink — twin-shed, double-side embossed, 1200 GSM. Plush enough for January in north India, light enough not to weigh down sleep.",
    fabric: "100% Polyester Mink",
    weave: "Embossed double-shed",
    origin: "Panipat, India",
    care: ["Machine wash cold", "Do not iron", "Tumble dry low"],
    sizes: ["Double (220 × 240 cm)", "King (240 × 260 cm)"],
    colors: [ROYAL, MIDNIGHT, GRAPHITE],
    images: [IMG.mink1, IMG.mink2],
  },
  {
    id: "p9",
    slug: "regalia-single-mink",
    name: "Regalia Single Mink",
    category: "Mink Blankets",
    price: 5490,
    tag: "New",
    shortDescription: "Single-bed mink, 900 GSM, brushed both sides.",
    description:
      "A clean, single-bed mink in 900 GSM. Brushed both sides for that pet-soft feel without bulk.",
    fabric: "100% Polyester Mink",
    weave: "Single-shed brushed",
    origin: "Panipat, India",
    care: ["Cold wash gentle cycle", "Air dry"],
    sizes: ["Single (152 × 220 cm)"],
    colors: [SLATE, ROSE, BONE],
    images: [IMG.mink1],
  },
  {
    id: "p10",
    slug: "noble-faux-fur-mink",
    name: "Noble Faux-Fur Mink",
    category: "Mink Blankets",
    price: 12490,
    tag: "Heirloom",
    shortDescription: "Faux-fur reverse on satin-finish mink. Show piece.",
    description:
      "Statement weight. Faux-fur on the reverse, satin-finish mink on the face. Made for cold mornings on a sofa, not just a bed.",
    fabric: "Polyester Faux Fur / Satin Mink",
    weave: "Bonded two-layer",
    origin: "Panipat, India",
    care: ["Dry clean only"],
    sizes: ["Double", "King"],
    colors: [CHAMPAGNE, MIDNIGHT, IVORY],
    images: [IMG.mink2],
  },
  {
    id: "p11",
    slug: "dynasty-floral-mink",
    name: "Dynasty Floral Mink",
    category: "Mink Blankets",
    price: 7290,
    shortDescription: "Floral-embossed mink, 1000 GSM, double bed.",
    description:
      "A floral-embossed face panel against a tonal indigo ground. 1000 GSM with a soft, even drape.",
    fabric: "100% Polyester Mink",
    weave: "Floral emboss",
    origin: "Panipat, India",
    care: ["Cold machine wash", "Tumble dry low"],
    sizes: ["Double", "Queen"],
    colors: [ROYAL, ROSE, MOSS],
    images: [IMG.mink1, IMG.mink2],
  },
  {
    id: "p12",
    slug: "heritage-mink-throw",
    name: "Heritage Mink Throw",
    category: "Mink Blankets",
    price: 3990,
    shortDescription: "Sofa-throw mink. Brushed face, hemmed edge.",
    description:
      "A throw-sized mink for sofas and reading chairs. 750 GSM, brushed face, neat hemmed edge.",
    fabric: "100% Polyester Mink",
    weave: "Brushed",
    origin: "Panipat, India",
    care: ["Cold wash", "Tumble dry low"],
    sizes: ["152 × 203 cm"],
    colors: [BONE, GRAPHITE, ROYAL],
    images: [IMG.mink1],
  },
  {
    id: "p13",
    slug: "sovereign-king-mink",
    name: "Sovereign King Mink",
    category: "Mink Blankets",
    price: 13990,
    mrp: 16500,
    tag: "Limited",
    shortDescription: "King-bed mink, 1500 GSM. Maximum loft.",
    description:
      "The heavy one. 1500 GSM mink, cut for king beds with full hang on both sides. Sleep through any cold night.",
    fabric: "100% Polyester Mink",
    weave: "Heavy double-shed",
    origin: "Panipat, India",
    care: ["Dry clean recommended"],
    sizes: ["King (240 × 260 cm)", "Super King (260 × 280 cm)"],
    colors: [MIDNIGHT, ROYAL, CHAMPAGNE],
    images: [IMG.mink2, IMG.mink1],
  },

  // ============ CUSHION COVERS (6) ============
  {
    id: "p14",
    slug: "dynasty-velvet-cushion-cover",
    name: "Dynasty Velvet Cushion Cover",
    category: "Cushion Covers",
    price: 1490,
    tag: "Bestseller",
    shortDescription: "Cotton velvet cushion cover with concealed zip.",
    description:
      "Cotton velvet face, cotton twill reverse, concealed YKK zip. Sold as a single cover; insert sold separately.",
    fabric: "Cotton Velvet / Twill Reverse",
    weave: "Velvet",
    origin: "Karur, India",
    care: ["Cold hand wash", "Iron reverse"],
    sizes: ["45 × 45 cm", "60 × 60 cm"],
    colors: [ROYAL, ROSE, MOSS, CHAMPAGNE],
    images: [IMG.cushion1],
  },
  {
    id: "p15",
    slug: "noble-jacquard-cushion-cover",
    name: "Noble Jacquard Cushion Cover",
    category: "Cushion Covers",
    price: 1690,
    shortDescription: "Tonal jacquard cushion cover, royal piping.",
    description:
      "Jacquard-woven tonal motif with a hand-applied royal-blue piping along all four edges.",
    fabric: "Cotton Jacquard",
    weave: "Jacquard",
    origin: "Karur, India",
    care: ["Spot clean", "Cool wash"],
    sizes: ["45 × 45 cm"],
    colors: [ROYAL, CHAMPAGNE, IVORY],
    images: [IMG.cushion2],
  },
  {
    id: "p16",
    slug: "imperial-embroidered-cushion-cover",
    name: "Imperial Embroidered Cushion Cover",
    category: "Cushion Covers",
    price: 2290,
    tag: "New",
    shortDescription: "Hand-embroidered crest on raw silk-blend.",
    description:
      "A hand-embroidered crest in champagne thread on a raw silk-blend ground. Each piece carries small variations from the artisan's hand.",
    fabric: "Silk-Cotton Blend",
    weave: "Plain weave",
    origin: "Bhuj, India",
    care: ["Dry clean only"],
    sizes: ["45 × 45 cm"],
    colors: [IVORY, ROYAL],
    images: [IMG.cushion1],
  },
  {
    id: "p17",
    slug: "heritage-printed-cushion-pair",
    name: "Heritage Printed Cushion Cover (Pair)",
    category: "Cushion Covers",
    price: 1890,
    mrp: 2400,
    shortDescription: "Pair of hand-block printed cotton cushion covers.",
    description:
      "A pair of hand-block printed cushion covers in vegetable-dye indigo. Concealed zip, twill reverse.",
    fabric: "Pure Cotton",
    weave: "Plain weave",
    origin: "Bagru, Rajasthan",
    care: ["Cold wash separately"],
    sizes: ["45 × 45 cm"],
    colors: [ROYAL, BONE, ROSE],
    images: [IMG.cushion2, IMG.cushion1],
  },
  {
    id: "p18",
    slug: "regalia-lumbar-cushion-cover",
    name: "Regalia Lumbar Cushion Cover",
    category: "Cushion Covers",
    price: 1790,
    shortDescription: "Long lumbar cover, 30 × 60 cm. Sateen face.",
    description:
      "Long lumbar cushion cover in 300 TC cotton sateen, finished with hand-stitched piping in champagne.",
    fabric: "300 TC Cotton Sateen",
    weave: "Sateen",
    origin: "Coimbatore, India",
    care: ["Cool machine wash"],
    sizes: ["30 × 60 cm"],
    colors: [PEARL, ROYAL, GRAPHITE],
    images: [IMG.cushion1],
  },
  {
    id: "p19",
    slug: "sovereign-tasselled-cushion-cover",
    name: "Sovereign Tasselled Cushion Cover",
    category: "Cushion Covers",
    price: 2490,
    tag: "Heirloom",
    shortDescription: "Hand-knotted tassels on heavyweight twill.",
    description:
      "Four hand-knotted champagne tassels on a heavyweight cotton twill ground. A statement on plain sofas.",
    fabric: "Heavy Cotton Twill",
    weave: "Twill",
    origin: "Bhuj, India",
    care: ["Spot clean", "Dry clean preferred"],
    sizes: ["50 × 50 cm"],
    colors: [MIDNIGHT, ROYAL, CHAMPAGNE],
    images: [IMG.cushion2],
  },

  // ============ PILLOW COVERS (6) ============
  {
    id: "p20",
    slug: "atelier-sateen-pillow-cover-pair",
    name: "Atelier Sateen Pillow Cover (Pair)",
    category: "Pillow Covers",
    price: 1290,
    tag: "Bestseller",
    shortDescription: "Pair of 400 TC sateen pillow covers, envelope close.",
    description:
      "Pair of 400 TC long-staple cotton sateen pillow covers with a clean envelope close — no buttons, no zips.",
    fabric: "400 TC Cotton Sateen",
    weave: "Sateen",
    origin: "Coimbatore, India",
    care: ["Cool wash", "Tumble dry low"],
    sizes: ["50 × 75 cm"],
    colors: [PEARL, ROYAL, GRAPHITE, BONE],
    images: [IMG.pillow1],
  },
  {
    id: "p21",
    slug: "regalia-percale-pillow-cover-pair",
    name: "Regalia Percale Pillow Cover (Pair)",
    category: "Pillow Covers",
    price: 1190,
    shortDescription: "400 TC percale pillow covers, matte finish.",
    description:
      "Percale weave with a matte, hotel-grade hand. Cool through the night, presses to a clean finish.",
    fabric: "400 TC Cotton Percale",
    weave: "Percale",
    origin: "Karur, India",
    care: ["Cool wash", "Iron damp"],
    sizes: ["50 × 75 cm"],
    colors: [IVORY, SLATE, ROYAL],
    images: [IMG.pillow2],
  },
  {
    id: "p22",
    slug: "noble-piped-pillow-cover-pair",
    name: "Noble Piped Pillow Cover (Pair)",
    category: "Pillow Covers",
    price: 1490,
    shortDescription: "Pair with hand-applied royal-blue piping.",
    description:
      "Sateen pillow covers with a hand-applied royal-blue piping along the closing edge.",
    fabric: "320 TC Cotton Sateen",
    weave: "Sateen",
    origin: "Coimbatore, India",
    care: ["Cool wash", "Iron warm"],
    sizes: ["50 × 75 cm"],
    colors: [PEARL, IVORY],
    images: [IMG.pillow1, IMG.pillow2],
  },
  {
    id: "p23",
    slug: "dynasty-printed-pillow-cover-pair",
    name: "Dynasty Printed Pillow Cover (Pair)",
    category: "Pillow Covers",
    price: 990,
    mrp: 1300,
    shortDescription: "Pair of hand-block printed cotton pillow covers.",
    description:
      "Hand-block printed in Bagru. 200 TC pure cotton with a soft hand. Sold as a pair.",
    fabric: "200 TC Pure Cotton",
    weave: "Plain weave",
    origin: "Bagru, Rajasthan",
    care: ["Cold wash separately first time"],
    sizes: ["50 × 75 cm"],
    colors: [ROYAL, ROSE, BONE],
    images: [IMG.pillow2],
  },
  {
    id: "p24",
    slug: "imperial-jacquard-pillow-cover-pair",
    name: "Imperial Jacquard Pillow Cover (Pair)",
    category: "Pillow Covers",
    price: 1890,
    tag: "New",
    shortDescription: "Tonal jacquard motif on long-staple cotton.",
    description:
      "Pair of pillow covers with tonal jacquard motifs that catch light when you turn the pillow.",
    fabric: "350 TC Cotton Jacquard",
    weave: "Jacquard",
    origin: "Coimbatore, India",
    care: ["Cool wash", "Iron reverse"],
    sizes: ["50 × 75 cm"],
    colors: [ROYAL, CHAMPAGNE, IVORY],
    images: [IMG.pillow1],
  },
  {
    id: "p25",
    slug: "heritage-bolster-pillow-cover",
    name: "Heritage Bolster Pillow Cover",
    category: "Pillow Covers",
    price: 1390,
    shortDescription: "Long bolster cover with end ties.",
    description:
      "A long bolster cover with woven end ties. Built for traditional Indian beds and large king setups.",
    fabric: "300 TC Cotton",
    weave: "Plain weave",
    origin: "Karur, India",
    care: ["Cool machine wash"],
    sizes: ["30 × 90 cm"],
    colors: [IVORY, ROYAL, MIDNIGHT],
    images: [IMG.pillow2],
  },

  // ============ SUMMER SETS (6) ============
  {
    id: "p26",
    slug: "monsoon-summer-set-3pc",
    name: "Monsoon Summer Set (3-Piece)",
    category: "Summer Sets",
    price: 4990,
    tag: "New",
    shortDescription: "Lightweight bedsheet + two pillow covers, breathable cotton.",
    description:
      "A 3-piece summer ensemble: one flat bedsheet and two pillow covers in 200 TC breathable cotton voile.",
    fabric: "200 TC Cotton Voile",
    weave: "Plain weave",
    origin: "Erode, India",
    care: ["Cold machine wash", "Air dry preferred"],
    sizes: ["Double", "Queen", "King"],
    colors: [BONE, SLATE, IVORY],
    images: [IMG.set1],
  },
  {
    id: "p27",
    slug: "atelier-summer-set-4pc",
    name: "Atelier Summer Set (4-Piece)",
    category: "Summer Sets",
    price: 6990,
    tag: "Bestseller",
    shortDescription: "Fitted + flat sheet + 2 pillow covers, 280 TC percale.",
    description:
      "Four piece summer set in 280 TC cotton percale — fitted sheet, flat sheet, two pillow covers. Cool, matte and crisp.",
    fabric: "280 TC Cotton Percale",
    weave: "Percale",
    origin: "Karur, India",
    care: ["Cool wash", "Tumble dry low"],
    sizes: ["Queen", "King"],
    colors: [PEARL, ROYAL, IVORY],
    images: [IMG.set1, IMG.sheet2],
  },
  {
    id: "p28",
    slug: "noble-block-print-summer-set",
    name: "Noble Block-Print Summer Set",
    category: "Summer Sets",
    price: 5990,
    shortDescription: "Hand-block printed 3-piece set, vegetable indigo.",
    description:
      "Hand-block printed in Bagru on 200 TC cotton. Soft, breathable, and the colour deepens with each wash.",
    fabric: "200 TC Pure Cotton",
    weave: "Plain weave",
    origin: "Bagru, Rajasthan",
    care: ["Cold wash separately first time"],
    sizes: ["Double", "Queen"],
    colors: [ROYAL, ROSE, BONE],
    images: [IMG.set1],
  },
  {
    id: "p29",
    slug: "regalia-jaipuri-summer-set",
    name: "Regalia Jaipuri Summer Set",
    category: "Summer Sets",
    price: 4490,
    mrp: 5800,
    shortDescription: "Jaipuri-print bedsheet with two matching pillow covers.",
    description:
      "Classic Jaipuri florals printed on lightweight cotton. Three pieces, ready for warm nights.",
    fabric: "180 TC Cotton",
    weave: "Plain weave",
    origin: "Jaipur, India",
    care: ["Cold wash", "Mild detergent"],
    sizes: ["Double", "Queen"],
    colors: [SAFFRON, ROSE, ROYAL],
    images: [IMG.sheet3],
  },
  {
    id: "p30",
    slug: "dynasty-linen-summer-set",
    name: "Dynasty Linen Summer Set",
    category: "Summer Sets",
    price: 8990,
    tag: "Limited",
    shortDescription: "Pure linen 3-piece set. Lived-in feel from day one.",
    description:
      "Stone-washed pure linen. Wrinkles by design. Three pieces — one flat sheet and two pillow covers.",
    fabric: "100% Pure Linen, Stone-washed",
    weave: "Plain weave",
    origin: "Coimbatore, India",
    care: ["Cool machine wash", "Air dry"],
    sizes: ["Queen", "King"],
    colors: [BONE, SLATE, IVORY],
    images: [IMG.set1],
  },
  {
    id: "p31",
    slug: "heritage-stripe-summer-set",
    name: "Heritage Stripe Summer Set",
    category: "Summer Sets",
    price: 5490,
    shortDescription: "Yarn-dyed champagne stripe set, 3 pieces.",
    description:
      "Yarn-dyed champagne pinstripes on a 240 TC cotton ground. Quiet, hotel-grade summer bedding.",
    fabric: "240 TC Yarn-dyed Cotton",
    weave: "Plain weave",
    origin: "Erode, India",
    care: ["Cool wash", "Iron warm"],
    sizes: ["Double", "Queen", "King"],
    colors: [IVORY, BONE],
    images: [IMG.sheet2],
  },

  // ============ WINTER SETS (7) ============
  {
    id: "p32",
    slug: "imperial-winter-set-4pc",
    name: "Imperial Winter Set (4-Piece)",
    category: "Winter Sets",
    price: 12990,
    tag: "Bestseller",
    shortDescription: "Bedsheet + comforter + 2 pillow covers. Royal indigo.",
    description:
      "A 4-piece winter ensemble: bedsheet, mid-weight comforter, and two pillow covers — all in coordinating royal indigo.",
    fabric: "300 TC Cotton Shell",
    weave: "Sateen / Quilted",
    origin: "Panipat, India",
    care: ["Cold machine wash", "Tumble dry low"],
    sizes: ["Double", "Queen", "King"],
    colors: [ROYAL, MIDNIGHT, GRAPHITE],
    images: [IMG.set2, IMG.comforter1],
  },
  {
    id: "p33",
    slug: "regalia-winter-set-6pc",
    name: "Regalia Winter Set (6-Piece)",
    category: "Winter Sets",
    price: 18990,
    tag: "New",
    shortDescription: "Bedsheet + comforter + 2 pillow + 2 cushion covers.",
    description:
      "Six pieces, fully coordinated: bedsheet, comforter, two pillow covers, two cushion covers. The room dressed in one box.",
    fabric: "Cotton Sateen Shell",
    weave: "Sateen / Quilted",
    origin: "Panipat, India",
    care: ["Cold wash on bulk cycle"],
    sizes: ["Queen", "King"],
    colors: [ROYAL, CHAMPAGNE, IVORY],
    images: [IMG.set2],
  },
  {
    id: "p34",
    slug: "noble-winter-set-8pc",
    name: "Noble Winter Set (8-Piece)",
    category: "Winter Sets",
    price: 24990,
    mrp: 31000,
    tag: "Heirloom",
    shortDescription: "Sheet + comforter + duvet cover + 2 pillow + 2 cushion + bolster.",
    description:
      "An 8-piece winter ensemble. Built around an heirloom comforter with a removable duvet cover and matching accent textiles.",
    fabric: "350 TC Cotton Sateen / Quilted Shell",
    weave: "Sateen / Quilted",
    origin: "Panipat, India",
    care: ["Dry clean comforter", "Cold wash sheet & covers"],
    sizes: ["Queen", "King"],
    colors: [MIDNIGHT, ROYAL, CHAMPAGNE],
    images: [IMG.set2, IMG.comforter1],
  },
  {
    id: "p35",
    slug: "dynasty-winter-set-10pc",
    name: "Dynasty Winter Set (10-Piece)",
    category: "Winter Sets",
    price: 34990,
    tag: "Limited",
    shortDescription: "Full bed-in-a-box, 10 coordinated pieces.",
    description:
      "The complete bed: fitted sheet, flat sheet, comforter, duvet cover, two pillow covers, two pillow shams, two cushion covers. One royal-indigo wardrobe for the bedroom.",
    fabric: "350 TC Cotton Sateen / Quilted Shell / Velvet Accents",
    weave: "Mixed",
    origin: "Panipat, India",
    care: ["Dry clean comforter & velvet pieces", "Cold wash linens"],
    sizes: ["Queen", "King"],
    colors: [ROYAL, MIDNIGHT, CHAMPAGNE],
    images: [IMG.set2, IMG.comforter2],
  },
  {
    id: "p36",
    slug: "heritage-quilted-winter-set-5pc",
    name: "Heritage Quilted Winter Set (5-Piece)",
    category: "Winter Sets",
    price: 15990,
    shortDescription: "Quilted bedcover + bedsheet + 2 pillow + cushion cover.",
    description:
      "Hand-quilted bedcover layered over a 280 TC cotton bedsheet, with two pillow covers and a single cushion cover.",
    fabric: "280 TC Cotton / Quilted Cotton",
    weave: "Quilted",
    origin: "Bhuj, India",
    care: ["Cold wash gentle cycle"],
    sizes: ["Double", "Queen"],
    colors: [ROSE, MOSS, IVORY],
    images: [IMG.set2],
  },
  {
    id: "p37",
    slug: "atelier-velvet-winter-set-7pc",
    name: "Atelier Velvet Winter Set (7-Piece)",
    category: "Winter Sets",
    price: 21990,
    shortDescription: "Velvet-accent winter set, 7 pieces, queen/king.",
    description:
      "Cotton sateen base with cotton-velvet cushion and bolster accents. Seven pieces of warm, layered styling.",
    fabric: "300 TC Cotton Sateen / Cotton Velvet",
    weave: "Mixed",
    origin: "Karur, India",
    care: ["Cold wash linens", "Spot clean velvet"],
    sizes: ["Queen", "King"],
    colors: [ROYAL, CHAMPAGNE, GRAPHITE],
    images: [IMG.set2, IMG.cushion1],
  },
  {
    id: "p38",
    slug: "sovereign-winter-set-4pc",
    name: "Sovereign Winter Set (4-Piece)",
    category: "Winter Sets",
    price: 10990,
    shortDescription: "Entry winter set: bedsheet, comforter, 2 pillow covers.",
    description:
      "The everyday winter set. Mid-weight comforter, 280 TC cotton bedsheet, two coordinating pillow covers.",
    fabric: "280 TC Cotton Shell",
    weave: "Sateen / Quilted",
    origin: "Panipat, India",
    care: ["Cold machine wash", "Tumble dry low"],
    sizes: ["Single", "Double", "Queen"],
    colors: [SLATE, MIDNIGHT, BONE],
    images: [IMG.set2],
  },

  // ============ SUMMER COMFORTERS (6) ============
  {
    id: "p39",
    slug: "monsoon-summer-comforter",
    name: "Monsoon Summer Comforter",
    category: "Summer Comforters",
    price: 6490,
    tag: "Bestseller",
    shortDescription: "150 GSM cotton fill. Light cover for warm rooms.",
    description:
      "A summer-weight comforter with a 150 GSM cotton fill and a 200 TC voile shell. Drapes light, breathes through warm nights.",
    fabric: "200 TC Cotton Shell, Cotton Fill",
    weave: "Box-stitch quilted",
    origin: "Panipat, India",
    care: ["Cold machine wash", "Tumble dry low"],
    sizes: ["Single", "Double", "Queen", "King"],
    colors: [BONE, SLATE, IVORY],
    images: [IMG.comforter1],
  },
  {
    id: "p40",
    slug: "atelier-muslin-summer-comforter",
    name: "Atelier Muslin Summer Comforter",
    category: "Summer Comforters",
    price: 7990,
    tag: "New",
    shortDescription: "5-layer muslin comforter. Soft, airy, washable.",
    description:
      "Five layers of cotton muslin gauze stitched into a single airy comforter. Softens with each wash. Fully machine washable.",
    fabric: "100% Cotton Muslin",
    weave: "Muslin gauze",
    origin: "Karur, India",
    care: ["Machine wash cold", "Tumble dry low"],
    sizes: ["Double", "Queen"],
    colors: [PEARL, BONE, ROSE],
    images: [IMG.comforter1, IMG.comforter2],
  },
  {
    id: "p41",
    slug: "noble-printed-summer-comforter",
    name: "Noble Printed Summer Comforter",
    category: "Summer Comforters",
    price: 5990,
    mrp: 7500,
    shortDescription: "Hand-block printed summer comforter, vegetable indigo.",
    description:
      "Hand-block printed shell over a light cotton fill. Softens beautifully and the print deepens with use.",
    fabric: "Pure Cotton Shell, Cotton Fill",
    weave: "Quilted",
    origin: "Bagru, Rajasthan",
    care: ["Cold wash separately first time"],
    sizes: ["Double", "Queen"],
    colors: [ROYAL, ROSE, BONE],
    images: [IMG.comforter2],
  },
  {
    id: "p42",
    slug: "regalia-cotton-dohar",
    name: "Regalia Cotton Dohar",
    category: "Summer Comforters",
    price: 4490,
    shortDescription: "Three-layer cotton dohar. AC-room weight.",
    description:
      "A traditional three-layer cotton dohar. Light enough for AC rooms, soft enough to drape over a sofa.",
    fabric: "Pure Cotton, 3-layer",
    weave: "Quilted",
    origin: "Jaipur, India",
    care: ["Machine wash cold"],
    sizes: ["Single", "Double", "Queen"],
    colors: [SAFFRON, ROSE, ROYAL],
    images: [IMG.comforter1],
  },
  {
    id: "p43",
    slug: "dynasty-reversible-summer-comforter",
    name: "Dynasty Reversible Summer Comforter",
    category: "Summer Comforters",
    price: 6990,
    shortDescription: "Reversible solid + stripe shell, light cotton fill.",
    description:
      "Solid champagne on one side, fine ivory stripe on the other. Reversible shell, summer-weight cotton fill.",
    fabric: "240 TC Cotton, Cotton Fill",
    weave: "Reversible quilted",
    origin: "Erode, India",
    care: ["Cold wash", "Tumble dry low"],
    sizes: ["Double", "Queen", "King"],
    colors: [CHAMPAGNE, IVORY],
    images: [IMG.comforter2],
  },
  {
    id: "p44",
    slug: "heritage-linen-summer-comforter",
    name: "Heritage Linen Summer Comforter",
    category: "Summer Comforters",
    price: 9490,
    tag: "Heirloom",
    shortDescription: "Pure linen shell, cotton fill. Heirloom drape.",
    description:
      "Pure linen shell with a fine cotton fill. Drapes heavy without heat — built for monsoon and shoulder seasons.",
    fabric: "100% Linen Shell, Cotton Fill",
    weave: "Box-stitch quilted",
    origin: "Coimbatore, India",
    care: ["Cool machine wash", "Air dry"],
    sizes: ["Queen", "King"],
    colors: [BONE, SLATE, IVORY],
    images: [IMG.comforter1],
  },

  // ============ WINTER COMFORTERS (7) ============
  {
    id: "p45",
    slug: "imperial-winter-comforter",
    name: "Imperial Winter Comforter",
    category: "Winter Comforters",
    price: 14990,
    mrp: 18500,
    tag: "Bestseller",
    shortDescription: "Heavy down-alt fill, 350 GSM. Baffle-box build.",
    description:
      "A heavyweight winter comforter with a 350 GSM down-alternative fill in a baffle-box construction so loft stays where you put it.",
    fabric: "300 TC Cotton Shell, Down-Alt Fill",
    weave: "Baffle-box",
    origin: "Panipat, India",
    care: ["Cold machine wash on bulk cycle", "Tumble dry low with tennis balls"],
    sizes: ["Single", "Double", "Queen", "King"],
    colors: [IVORY, ROYAL, MIDNIGHT],
    images: [IMG.comforter2, IMG.comforter1],
  },
  {
    id: "p46",
    slug: "regalia-microfiber-winter-comforter",
    name: "Regalia Microfiber Winter Comforter",
    category: "Winter Comforters",
    price: 8990,
    tag: "New",
    shortDescription: "300 GSM microfiber fill. Quiet, lofty, washable.",
    description:
      "Microfiber fill in a quilted cotton-blend shell. Lofty, quiet, fully machine washable.",
    fabric: "Cotton-Polyester Shell, Microfiber Fill",
    weave: "Box-stitch quilted",
    origin: "Panipat, India",
    care: ["Cold machine wash", "Tumble dry low"],
    sizes: ["Single", "Double", "Queen"],
    colors: [SLATE, GRAPHITE, BONE],
    images: [IMG.comforter1],
  },
  {
    id: "p47",
    slug: "noble-velvet-winter-comforter",
    name: "Noble Velvet Winter Comforter",
    category: "Winter Comforters",
    price: 21990,
    tag: "Heirloom",
    shortDescription: "Velvet-faced winter comforter. Show piece for the bed.",
    description:
      "Cotton-velvet face panel with a heavy down-alt fill. Built as much for the look as the warmth.",
    fabric: "Cotton Velvet / Cotton Reverse, Down-Alt Fill",
    weave: "Quilted",
    origin: "Karur, India",
    care: ["Dry clean only"],
    sizes: ["Queen", "King"],
    colors: [ROYAL, MIDNIGHT, ROSE],
    images: [IMG.comforter2],
  },
  {
    id: "p48",
    slug: "dynasty-quilted-winter-comforter",
    name: "Dynasty Quilted Winter Comforter",
    category: "Winter Comforters",
    price: 12490,
    shortDescription: "Diamond-quilted shell, 320 GSM down-alt fill.",
    description:
      "Classic diamond-quilted cotton shell over a 320 GSM down-alt fill. Even loft, heavy drape.",
    fabric: "300 TC Cotton Shell, Down-Alt Fill",
    weave: "Diamond quilted",
    origin: "Panipat, India",
    care: ["Cold wash", "Tumble dry low"],
    sizes: ["Double", "Queen", "King"],
    colors: [PEARL, ROYAL, GRAPHITE],
    images: [IMG.comforter1, IMG.comforter2],
  },
  {
    id: "p49",
    slug: "sovereign-king-winter-comforter",
    name: "Sovereign King Winter Comforter",
    category: "Winter Comforters",
    price: 17990,
    shortDescription: "Oversized king comforter. 400 GSM down-alt fill.",
    description:
      "Cut generously for king beds with full hang on both sides. 400 GSM fill for sub-zero rooms.",
    fabric: "320 TC Cotton Shell, Heavy Down-Alt Fill",
    weave: "Baffle-box",
    origin: "Panipat, India",
    care: ["Dry clean recommended"],
    sizes: ["King (240 × 260 cm)", "Super King"],
    colors: [MIDNIGHT, ROYAL, IVORY],
    images: [IMG.comforter2],
  },
  {
    id: "p50",
    slug: "heritage-jacquard-winter-comforter",
    name: "Heritage Jacquard Winter Comforter",
    category: "Winter Comforters",
    price: 16990,
    shortDescription: "Tonal jacquard shell with heavy winter fill.",
    description:
      "Jacquard-woven tonal motifs across the shell, with a 350 GSM down-alt fill. Quiet pattern, decisive warmth.",
    fabric: "350 TC Cotton Jacquard, Down-Alt Fill",
    weave: "Jacquard / Baffle-box",
    origin: "Coimbatore, India",
    care: ["Dry clean preferred"],
    sizes: ["Queen", "King"],
    colors: [ROYAL, CHAMPAGNE, IVORY],
    images: [IMG.comforter1],
  },
  {
    id: "p51",
    slug: "atelier-reversible-winter-comforter",
    name: "Atelier Reversible Winter Comforter",
    category: "Winter Comforters",
    price: 13490,
    tag: "Limited",
    shortDescription: "Reversible solid/printed shell, 320 GSM fill.",
    description:
      "Solid royal indigo on one face, tonal printed motif on the reverse. Two looks, one heavyweight comforter.",
    fabric: "300 TC Cotton, Down-Alt Fill",
    weave: "Reversible quilted",
    origin: "Panipat, India",
    care: ["Cold wash on bulk cycle", "Tumble dry low"],
    sizes: ["Double", "Queen", "King"],
    colors: [ROYAL, MIDNIGHT, CHAMPAGNE],
    images: [IMG.comforter2, IMG.comforter1],
  },
];

export function formatPrice(p: number): string {
  return `₹${p.toLocaleString("en-IN")}`;
}

export function getProduct(slug: string) {
  return products.find((p) => p.slug === slug);
}

export function byCategory(cat: Category) {
  return products.filter((p) => p.category === cat);
}
